logging:
  level:
    root: info
    com.cloud: debug
  file: logs/${spring.application.name}.log
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.16.23:3306/cloud_file?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-test-query: SELECT 1
  rabbitmq:
    host: 172.16.16.23
    port: 15672
    username: guest
    password: cpy@2020
    virtual-host: /
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    servlet:
      load-on-startup: 1
  aop:
    proxy-target-class: true
  zipkin:
    base-url: http://172.16.16.23:9411
    enabled: true
    sender:
      type: web
mybatis:
  type-aliases-package: com.cloud.file.model
  mapper-locations: classpath:/mybatis-mappers/*
  configuration:
    mapUnderscoreToCamelCase: true
security:
  oauth2:
    resource:
      user-info-uri: http://172.16.16.23:8080/api-o/user-me
      prefer-token-info: false
file:
  local:
    path: d:/localFile
    prefix: /statics
    urlPrefix: http://172.16.16.23:8080/api-f${file.local.prefix}
  aliyun:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    accessKeyId: LTAIBwsB7NkxXlcg
    accessKeySecret: osCUjnZ2k1CJjUUJtNOxeC6RDpfJhB
    bucketName: cpy2019
    domain: https://img.cpucloud.com
    prefix: upload
  qcloud:
    domain: xxx
    prefix: xxx
    secretId: xxx
    secretKey: xxx
    region: xxx
    bucketName: xxx
  qiniu:
    domain: xxx
    prefix: xxx
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucketName: xxx




