logging:
  level:
    root: info
    com.cloud: debug
  file: logs/${spring.application.name}.log
spring:
  redis:
    host: 172.16.16.23
    port: 6379
    password: cpy@2020
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.16.23:3306/cloud_notification?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: cpy@2020
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-test-query: SELECT 1

  mail:
    host: smtp.exmail.qq.com
    port: 587
    sender: 创普云科技<noreply@cpucloud.com>
    username: noreply@cpucloud.com
    #QQ邮箱的授权码
    password: RYWBUZqsS5kwtShD
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  rabbitmq:
    host: 172.16.16.23
    port: 5672
    username: guest
    password: cpy@2020
    virtual-host: /
  mvc:
    servlet:
      load-on-startup: 1
  aop:
    proxy-target-class: true
  zipkin:
    base-url: http://172.16.16.23:9411
    enabled: true
    sender:
      type: web
mybatis:
  type-aliases-package: com.cloud.notification.model
  mapper-locations: classpath:/mybatis-mappers/*
  configuration:
    mapUnderscoreToCamelCase: true
security:
  oauth2:
    resource:
      user-info-uri: http://172.16.16.23:8080/api-o/user-me
      prefer-token-info: false
aliyun:
  accessKeyId: xxx
  accessKeySecret: xxx
  sign:
    name1: xxx
  template:
    code1: xxx
sms:
  expire-minute: 15
  day-count: 30