logging:
  level:
    root: info
    com.cloud: debug
  file: logs/${spring.application.name}.log
spring:
  rabbitmq:
    host: 172.16.16.23
    port: 5672
    username: guest
    password: cpy@2020
    virtual-host: /
  redis:
    host: 172.16.16.23
    port: 6379
    password: cpy@2020
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
  mvc:
    servlet:
      load-on-startup: 1
  aop:
    proxy-target-class: true
  zipkin:
    base-url: http://172.16.16.23:9411
    enabled: true
    sender:
      type: web
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

wxpay:
  wxpayAppId: wx06e5ce9adb7ef57a
  wxpaySecret: 8952e4a41c9f4bed3216bfe43830d285
  wxpayMcId: 1551167661
  wxpayApiKey: Qc10NtYEBJHUykaDq2SPML6EF2DPIc6a
  wxpayNotifyUrl: https://portal.cpucloud.com/cui/sys/pay/wxPayNotify
  wxCertName: /cert/apiclient_cert.p12
  uniformorder: https://api.mch.weixin.qq.com/pay/unifiedorder
  refundUrl: https://api.mch.weixin.qq.com/secapi/pay/refund
  transfersUrl: https://api.mch.weixin.qq.com/mmpaymkttransfers/promotion/transfers
  wxWebAccessTokenHttpsUrl: https://api.weixin.qq.com/sns/oauth2/access_token?appid=%s&secret=%s&code=%s&grant_type=authorization_code
  wxWebUserInfoHttpsUrl: https://api.weixin.qq.com/sns/userinfo?access_token=%s&openid=%s
  wxPayOrderqueryHttpsUrl: https://api.mch.weixin.qq.com/pay/orderquery
  wxPayOrderCloseorderHttpsUrl: https://api.mch.weixin.qq.com/pay/closeorder

alipay:
  alipayAppId: 2019081566201811
  alipayAppPrivateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDj2HEOeStkeIkHLVlkQE+0CF/ve8I/4acp2gACQzZ6F9wzSFUrb1EW5+6vSCZ/QHcPnZNg9zjyVKsOvZojUV0oGU5dRDDRhNusPX7HQjmMAuVFA6jkXbQsUG4/zHGs+c4202ZrjCTOc6CfUHohRAwF7iRvsPkEi6t948R5Fsnf21UzzI4yMfrGU2yTqSDV7/l294fPItlyrT9W2cNiK0Ci2OxTGek+I9ffWOnBj9ygosRUmfpYw8p3ws3nD9/kYWJGqwrZ3ihi4puWFATXK+KQQuo5Wat4g6MhdXy0Ra5fk9KRfhmhslUJxZ4l4kUTekACL3Emt1AcrjkV0sGIfEUZAgMBAAECggEAbonMV7w7bBP6TswWiUeWI37IpFQDaqCcS/aieHaJUHSQ9SRLhbYMvjMpnko/uw7YdG/7V1i5fP/MuWsNA8NukYytcxwpHwz40jhHcH5VkvK4rmHXJ2u6hKFEy5jxMX1EKV8oWlb0aGC6dXBCwC7WMm5VqQZP2X+1ZG8DG8gNipdg7149Fjna1cT4U6AWMRi4LeeZwKDZ2Kf8t8B/Ea8A9o6ocquNxjMHrGy5B4xGbOPFQX0uKC7XgNkD6Mih57SC98q5t0fxYWWiiJTHhCGTQVoWJRblBQkcXcrXpyOP7jVx9X512QyL+VgIhRvuki/OiCbIlLU7EIDR+9+mYRBBcQKBgQD4kt5LgOymlCkaqsNgf8aLbda4sahQbvYFnwJivGcYwgZZHiwE1Czwzr/SStNYTa1v45A9LPUudSHQfjl/p9hYcIUQ5SpxpEIYlLlOVkHR0FGkXX69Ya1u3xiVch4k0JX0NIGjtLEMwT8fvv/2WM9QeJCg0SazWSnwzXgQXZ8cXQKBgQDqpwpbW9gRhhrHljySrsEMAryqjyNREWu9J3uZWGXkBeUkVXc3Z08b0rwKN38wLwfUyipf9o3OBWkZBy74T98xZkg7VauBA4IV2zgz+uk/xYcLXNdYoNb7XhdC+2+ItPnbiaD50IwsA9yGp1NB92nyEvxgFUx3MnwKqpYklMLf7QKBgQDLN+9K1RUkPp64MYFXhD8CwIK6LmxHjd/Oyqe9pv+2avGbrCIatIglOzHxr8DHQYIYpnfGu9ma6KIDfR5u8f7alusC3AfuLnbm97fjhnt7GA+XC+TQ2Wlb6kKD828Xc/wUUVTnTJMutVJxFsrWUNb0mAzNnRBBshSqzKBq6M9q9QKBgCqmgfNpFjTZMzTj0c63hM8yECjQK5Mon3SaIJUWxC5WA/g+sJSZan+cJiGVRMD1S28Z7+nRXqT7xsaNz7PCkMbh2G8weyPQB20Bk42fJZY5yPn/vgSV931o9MFwAi3O9zs4INJHXbMCYKr47uEmn1MosEammGdx/anSp8euYl1hAoGBAPiFRv8fI3fRcj783ngaQD0mrL85aVRyl+vd34hnonjmu5mbIxqSokIvw1TmcJT5nZRtB2cgKjAzNjnXR1gkBqU3Im2+8UO4RqNXfCWvVi3P/AZ8w3TSJE/FAqLe6da0Dan90Vj7koT+abPfJ+msiMkc4KIMXrJgJK1wxH9kHxdB
  alipayPublicKey: /++//DNa++
  alipayNotifyUrl: https://portal.cpucloud.com/cui/sys/pay/aliPayNotify
  timeoutExpress: 90m
  productCode: QUICK_MSECURITY_PAY
  pid:
  alipayUrl: https://openapi.alipay.com/gateway.do
  jumppath:
    accountPath: https://portal.cpucloud.com/user-account
    orderDetailpath: https://portal.cpucloud.com/order-order